# Generated by Django 3.0.6 on 2020-05-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='author')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
            options={
                'db_table': 'author',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('link', models.URLField(verbose_name='link')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('upvotes', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.Author', verbose_name='author')),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='content')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentAuthor', to='news.Author', verbose_name='author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentPost', to='news.Post', verbose_name='post')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['-creation_date'],
            },
        ),
    ]
